---
title: "Benefit and Burden: Pilot Data Analysis"
author: "Katie Cheng"
date: "November 2, 2016"
output: html_document
---

```{r Preliminaries, results = "hide", message = FALSE, warning = FALSE, echo=FALSE}

library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(knitr)
library(plyr)
library(nFactors) # factor analysis


summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else length(x)}
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N = length2(xx[[col]], na.rm=na.rm),
          mean = mean(xx[[col]], na.rm=na.rm),
          sd = sd(xx[[col]], na.rm=na.rm))},
      measurevar)
    datac <- plyr::rename(datac, c("mean" = measurevar))
    datac$se <- datac$sd / sqrt(datac$N)
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult
    return(datac)
}

```

```{r, echo=FALSE}

# Read in pilot data.

data <- read.csv("/Users/Katie/Desktop/Stanford/2016-17 Fall/CS 376 HCI Research/Benefit_Burden/benefit_burden/pilot/data/2016-11-01_pilot_survey_responses.csv")

items = names(data)[
intersect(
  intersect(
    intersect(
      union(grep("current_", names(data)), grep("abandoned_", names(data))),
      grep("_num", names(data), invert = TRUE)), 
    grep("category", names(data), invert=TRUE)), 
  grep("benefit", names(data), invert=TRUE))]

for(i in items){
data[[i]] = factor(data[[i]], levels = c("Never", "A little bit of the time", "Sometimes", "Very often", "All of the time"))
}

```

# Demographics

```{r, message = FALSE, echo=FALSE}

qplot(gender, data=data)
qplot(from, data=data)
qplot(age_num, data=data)
qplot(educ, data=data)
qplot(device, data=data)
qplot(usage, data=data)

```

# Average benefits by category

## Currently used app

```{r, fig.width=10, fig.height=6, warning = FALSE, echo=FALSE}

current_summ = summarySE(data, groupvars=c("current_category"), measurevar="current_benefit_score")

ggplot(data=current_summ, #[current_summ$N > 5,]
       aes(x=current_category, y=current_benefit_score,
           fill=current_category, label=paste("n=", N, sep=''))) + 
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(
    ymin = current_benefit_score-se,
    ymax = current_benefit_score+se), 
    width = .2, position=position_dodge(.9)) + 
  geom_text(y = 0.1, size=3) +
  expand_limits(y=c(0,1))

```

## Abandoned app

```{r, fig.width=10, fig.height=6, warning = FALSE, echo=FALSE}

abandoned_summ = summarySE(data, groupvars=c("abandoned_category"), measurevar="abandoned_benefit_score")

abandoned_summ = filter(abandoned_summ, abandoned_category!="")

ggplot(data=abandoned_summ, #[abandoned_summ$N > 5,]
       aes(x=abandoned_category, y=abandoned_benefit_score,
           fill=abandoned_category, label=paste("n=", N, sep=''))) + 
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(
    ymin = abandoned_benefit_score-se,
    ymax = abandoned_benefit_score+se), 
    width = .2, position=position_dodge(.9)) + 
  geom_text(y = 0.1, size=3) +
  expand_limits(y=c(0,1))

```

